services:
  # 1. THE BACKEND (API)
  - type: web
    name: stockticker-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: static
          name: stockticker-ui
          property: host

  # 2. THE FRONTEND (UI)
  - type: static
    name: stockticker-ui
    runtime: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: stockticker-api
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html


databases:
  - name: stock-db
    plan: free
